name: Run Fund Monitor

on:
  schedule:
    # Runs at 06:45 UTC (14:45 Beijing Time) every day from Monday to Friday
    - cron: '45 6 * * 1-5'
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create user_config.json from Secrets
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          RECEIVER_EMAILS: ${{ secrets.RECEIVER_EMAILS }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: |
          echo '{' > user_config.json
          echo '  "email": {' >> user_config.json
          echo '    "smtp_server": "'$SMTP_SERVER'",' >> user_config.json
          echo '    "smtp_port": '$SMTP_PORT',' >> user_config.json
          echo '    "sender_email": "'$SENDER_EMAIL'",' >> user_config.json
          echo '    "password": "'$EMAIL_PASSWORD'",' >> user_config.json
          echo '    "receiver_emails": ["'$RECEIVER_EMAILS'"]' >> user_config.json
          echo '  }' >> user_config.json
          echo '}' >> user_config.json

      - name: Run monitor script
        env:
          TZ: Asia/Shanghai
        run: python monitor.py